image: node:20

stages:
  - build
  - deploy

variables:
  SOURCE_DIR: "dist/firefox"
  ADDON_ID: $ADDON_ID

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
  policy: pull-push

before_script:
  - corepack enable pnpm
  - pnpm config set store-dir .pnpm-store

build_firefox_addon:
  stage: build
  script:
    - echo "Installing dependencies with pnpm..."
    - pnpm install --frozen-lockfile
    - echo "Building Firefox add-on using pnpm build:firefox..."
    - pnpm build:firefox
  artifacts:
    paths:
      - $SOURCE_DIR
    expire_in: 1 day

deploy_to_mozilla_amo:
  stage: deploy
  dependencies:
    - build_firefox_addon
  script:
    - echo "Installing web-ext tool globally..."
    - npm install -g web-ext
    - echo "Submitting add-on to Mozilla AMO for review..."
    - web-ext sign --api-key $WEB_EXT_API_KEY --api-secret $WEB_EXT_API_SECRET --source-dir $SOURCE_DIR --id $ADDON_ID
    - echo "Add-on submission process initiated. Check AMO developer hub for the status of your submission."
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success