name: Publish Hikka Forge Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v0.2.5
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create output directory
        run: mkdir -p .output

      - name: Build for Chrome
        run: |
          pnpm build:chrome
          zip -r .output/chrome-extension.zip dist/chrome/

      - name: Build for Firefox
        run: |
          pnpm build:firefox
          zip -r .output/firefox-extension.xpi dist/firefox/
          zip -r .output/firefox-sources.zip .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-builds
          path: .output/

  publish-to-stores:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-builds
          path: .output

      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: .output/chrome-extension.zip
          extension-id: ${{ secrets.CWS_EXTENSION_ID }}
          client-id: ${{ secrets.CWS_CLIENT_ID }}
          client-secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CWS_REFRESH_TOKEN }}
          publish: true

      - name: Publish to Firefox Add-ons (AMO)
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: ${{ secrets.AMO_EXTENSION_ID }}
          addon-path: .output/firefox-extension.xpi
          source-path: .output/firefox-sources.zip
          approval-note: |
            The source project requires Node.js 18.x and pnpm.
            To generate the add-on, please run:
              pnpm install && pnpm build:firefox
          release-note: |
            Version ${{ github.ref_name }} has been released with new features and bug fixes.
          auth-api-issuer: ${{ secrets.AMO_JWT_ISSUER }}
          auth-api-secret: ${{ secrets.AMO_JWT_SECRET }}
